### ISSUE TITLE
Must restart pow after every page load when using HTTPS

### ISSUE THREAD

**Issue by aarongray** [basecamp/powprox#10]
Cool repo. Everything works for me, except that I have to `touch ~/.pow/restart.txt` after every page load. If I don't, every subsequent page load request seems to go off in the weeds and generally 504's. If I switch over to HTTP, everything works as expected - it only happens with HTTPS. Any ideas?

**Comment by jeremy** [comment]
Smells like you have a HTTPS→HTTP redirect loop or something? Would need to check your nginx and app logs to see what's happening.

**Comment by aarongray** [comment]
Thanks for the tip. I'll report back if I'm able to get any more intel to work with on this issue.

**Comment by aarongray** [comment]
Okay got some new info. I am using puma and nginx. When the issue occurs and the request goes off and 504's, I am not seeing anything come over in the logs on my development environment. I am logging to STDOUT and can see the rails logs and puma logs just fine, but I don't see anything appear in those logs when the request goes off in the weeds.

Here are the nginx logs when the request 504's:

```
2017/12/27 12:12:54 [error] 98#0: *286 upstream timed out (60: Operation timed out) while reading response header from upstream, client: 127.0.0.1, server: ~^(?<pow_host>.+).dev$, request: "GET /assets/example-app-logo.svg HTTP/2.0", upstream: "http://127.0.0.1:20559/assets/example-app-logo.svg", host: "example.dev", referrer: "https://example.dev/798819214b/vehicles"
2017/12/27 12:15:36 [error] 98#0: *286 upstream timed out (60: Operation timed out) while reading response header from upstream, client: 127.0.0.1, server: ~^(?<pow_host>.+).dev$, request: "GET /798819214b/vehicles HTTP/2.0", upstream: "http://127.0.0.1:20559/798819214b/vehicles", host: "example.dev"
```

Any thoughts?
