### ISSUE TITLE
Trusting pow root ca and server cert?

### ISSUE THREAD

**Issue by bf4** [basecamp/powprox#5]
On OSX 10.10.5 Yosemite MBP Mid 2015 at 0f7c102faa5add1eb5d5688e6caaa08192484147

I've had issues with chrome not trusting the server cert

[powprox-create-root-cata](https://github.com/basecamp/powprox/blob/0f7c102faa5add1eb5d5688e6caaa08192484147/libexec/powprox-create-root-ca#L31) runs `security add-trusted-cert -d -r trustRoot -k "$HOME/Library/Keychains/login.keychain" "$POWPROX_DIR/ssl/ca/pow-root-ca.crt"`

but [powprox-create-server-certificate](https://github.com/basecamp/powprox/blob/0f7c102faa5add1eb5d5688e6caaa08192484147/libexec/powprox-create-server-certificate) does not.

I had been doing some manual stuff

``` plain
# UNTRUSTED CERT IN CHROME
# Search pow in Keychain.
# If present, click, command+I, edit trust settings to always trust
# Else,
#  1. click on the https with the / through it in the address bar
#  2. click view certificate
#  3. drag the picture of the cert to the desktop (or another folder)
#  4. double click it to import it to the Keychain
#  5. edit trust settings to always trust as above
#
# Else restart chrome
# go to 'chrome://flags' and
# Try: Enable 'Allow invalid certificates for resources loaded from localhost.'
# Try: 'Mark non-secure origins as non-secure' as 'neutral'
```

but why doesn't the script `sudo security add-trusted-cert -d -r trustRoot -k "$HOME/Library/Keychains/login.keychain" "$POWPROX_DIR/ssl/certs/pow-server.crt"`. Am I doing something wrong?

Also, I had to

``` bash
  # https://github.com/basecamp/pow/issues/480#issuecomment-62254317
  sudo sysctl -w net.inet.ip.forwarding=1;
  sudo echo "rdr pass proto tcp from any to any port {80,20559} -> 127.0.0.1 port 20559" | sudo pfctl -a "com.apple/250.PowFirewall" -Ef -
  # sudo pfctl -f /etc/pf.conf; sudo pfctl -e
```

to get the port 80 forwarding working.

In debugging this, I ended up writing a [`setup-pow`](https://gist.github.com/bf4/75e7b9b89bc823019a1d) script to uninstall everything, reinstall it, and confirm success.  It's not perfect but has worked for me when something goes wrong for unknown reasons.

**Comment by jeremy** [comment]
We don't explicitly trust the server cert because it's trusted via the CA root that we generate once, up front. That way we only have to `sudo` once and can freely create fresh server certs without filling the keychain with garbage certs.

If you're having issues with Chrome not trusting the root CA cert, focus on that aspect of troubleshooting. Try to manually trust that cert, for example. On OS X this should "just work" with Keychain, though!

**Comment by bf4** [comment]
@jeremy 

> If you're having issues with Chrome not trusting the root CA cert, focus on that aspect of troubleshooting. Try to manually trust that cert, for example. On OS X this should "just work" with Keychain, though!

yeah, but it's not.  Manually trusting the cert works, but I shouldn't have to do that, right? I put some amount of time into this, and this is what I wound up with. 

Do you think a reinstall or uninstall command would be useful? I think I have the guts of that here

**Comment by jeremy** [comment]
@bf4 Right, shouldn't have to manually trust individual certs, just the root CA we generate. Still curious what/why you hit here, whether with Keychain, Chrome, or cert signing 😊
